// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

interface {{hwif.interface_name}} #( 
	{%- for param in keep_params %}
        parameter {{kwf(param)}} {% if not loop.last %}, {%-endif%}		{# galaviel no comma on last param.. #}
    {%- endfor %}
	);
    {{hwif.get_interface_contents()|indent}}
    
    addrmap_top__in_t   in_struct;
    addrmap_top__out_t  out_struct;
    modport in ( input  in_struct );
    modport out( output out_struct);    

endinterface
